name: "Pixelcart Dev - iOS"

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.32.2

      - name: Install Dependencies
        run: flutter pub get

      - name: Clean and Install iOS Pods
        run: |
          cd ios
          sudo gem install cocoapods
          pod repo update
          rm -rf Pods Podfile.lock
          pod cache clean --all
          pod install
          cd ..

      - name: Create env File
        run: |
          touch .env
          echo STRIPE_TEST_PUBLISHABLE_KEY=${{ secrets.STRIPE_TEST_PUBLISHABLE_KEY }} >> .env
          echo STRIPE_TEST_SECRET_KEY=${{ secrets.STRIPE_TEST_SECRET_KEY }} >> .env

      - name: Generate Required Files
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Run Test
        run: flutter test

      - name: Build iOS
        run: flutter build ios --simulator

      - name: Upload iOS
        uses: actions/upload-artifact@v4
        with:
          name: ios-dev-app
          path: build/ios/iphonesimulator/
